name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         issue-message: "**Hi there! 👋** Thank you for opening this issue. Our team will take a look as soon as possible and get back to you. We truly appreciate your effort in improving **Pouranik**! 🌟"
         pr-message: "🎉 **Thanks for your pull request!** We’ll review it shortly. Your contribution means a lot to the project!✨"
